# Generated by Django 4.2.2 on 2023-07-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='page_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='page/'),
        ),
    ]
