# Generated by Django 4.2.2 on 2023-07-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_customuser_page_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='public_visibility',
            field=models.BooleanField(default=False),
        ),
    ]
