# Generated by Django 4.2.2 on 2023-07-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_customuser_public_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=300, max_digits=8),
        ),
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='visibility',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='year_published',
            field=models.IntegerField(default=2023),
        ),
    ]
