# Generated by Django 4.2.2 on 2023-07-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_customuser_cost_customuser_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(default='N/A')),
                ('visibility', models.CharField(max_length=100, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=300, max_digits=8)),
                ('year_published', models.IntegerField(default=2023)),
                ('file', models.FileField(null=True, upload_to='uploads/')),
                ('username', models.CharField(max_length=255)),
                ('page_image', models.FileField(default=None, max_length=250, null=True, upload_to='page/')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='description',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='file',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='page_image',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='title',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='visibility',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='year_published',
        ),
    ]
