# Generated by Django 4.2.2 on 2023-07-05 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_uploadedfile_remove_customuser_cost_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
