# Generated by Django 4.2.2 on 2023-07-05 11:04

from django.db import migrations
import page.models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', page.models.CustomUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='page_image',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='username',
        ),
    ]
