# Generated by Django 4.2.2 on 2023-07-05 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
