# Generated by Django 4.2.2 on 2023-07-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_uploadedfile_uploaded_at_uploadedfile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='cost',
            field=models.PositiveIntegerField(default=300, max_length=8),
        ),
    ]
