# Generated by Django 4.2.2 on 2023-07-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_alter_uploadedfile_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='cost',
            field=models.PositiveIntegerField(),
        ),
    ]
