# Generated by Django 4.2.2 on 2023-07-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0013_alter_uploadedfile_year_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='year_published',
            field=models.IntegerField(default=2023),
        ),
    ]
