# Generated by Django 4.2.2 on 2023-07-11 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0014_alter_uploadedfile_year_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='visibility',
            new_name='public_visibility',
        ),
    ]
